# componentDidCatch

: 기본적으로 컴포넌트의 예외 처리라 볼 수 있으며,  
우리가 개발단계에서 보는 에러페이지는 사용자 에게 보여 지지 않습니다.  
그래서 사용자는 빈 페이지를 보게 될 것이며, 개발자는 사용자가 당황하지 않도록  
에러페이지를 생성해 보여 줄 수 있도록 합니다.

물론 에러의 예외처리는 기본적으로 코드에서 작성하나, 다른 에러도 있을수 있으므로,  
어떠한 에러인지 빨리 캐치하기 위햐여 사용합니다.

### App.js

```
import React from 'react';
import './App.css';
import User from './User';
import ErrorBoundary from './ErrorBoundary';

function App() {
  const user = {
    id: 1,
    username: 'park',
  };

  return (
    <ErrorBoundary>
      {/* ErrorBoundary 컴포넌트로 User 컴포넌트를 감싸는 이유는 */}
      {/* 에러 발생 예외처리를 ErrorBoundary 컴포넌트에서 진행중이고 */}
      {/* ErrorBoundary 안쪽에 있는 컴포넌트가 모두 랜더가 되어야 */}
      {/* /ErrorBoundary 로 인해 ErrorBoundary 컴포넌트도 랜더가 종료 됩니다. */}
      <User />
    </ErrorBoundary>
  );
}

export default App;
```

### User.js

```
import React from 'react';

const User = ({ user }) => {
  //  if (!user) return null;
  // 기본적으로 코드에서 예외처리 해줌을 원칙으로 하지만...
  // 만약에 에러가 발생했다면... 개발자의 에러캐치와 사용자에게
  // 에러가 발생했음을 알려 주어야 합니다.

  // 에러의 원인 props으로 받아오는 user가 넘어오지 않아 에러 페이지가 나타나는데
  // 이는 개발서버에서 생성해주는 메시지 이며, 사용 자는 에러페이지 를 껏을때 나타나는
  // 빈 페이지만 보여 당황 스럽습니다.
  return (
    <div>
      <div>
        <b>ID</b>: {user.id}
      </div>
      <div>
        <b>Username</b>: {user.username}
      </div>
    </div>
  );
};

export default User;
```

### ErrorBoundary.

```
import React, { Component } from 'react';

class ErrorBoundary extends Component {
  state = {
    error: false,
  };

  componentDidCatch(error, info) {
    console.log('에러가 발생했습니다.');
    console.log({
      error,
      info,
    });
    this.setState({
      error: true,
    });
  }

  render() {
    if (this.state.error) return <h1>에러 발생!</h1>;
    return this.props.children;
  }
}

/*
 <ErrorBoundary>
    <User />
 </ErrorBoundary>
*/
// ErrorBoundary 컴포넌트로 User 컴포넌트를 감싸는 이유는
// 에러 발생 예외처리를 ErrorBoundary 컴포넌트에서 진행중이고
// ErrorBoundary 안쪽에 있는 컴포넌트가 모두 랜더가 되어야
// /ErrorBoundary 로 인해 ErrorBoundary 컴포넌트도 랜더가 종료 됩니다.

export default ErrorBoundary;
```
